name: eslint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    name: Run eslint scanning
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install eslint
        run: npm install eslint@8.57.0

      - name: Run eslint
        run: npx eslint . --config .eslintrc.yml --ext .js
