name: eslint

on:
  - push
  - pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    name: Run eslint scanning
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install eslint
        run: npm install eslint@8.57.0

      - name: Run eslint
        run: npx eslint .
          --config .eslintrc.js
          --ext .js
